// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ravjxdlkvjpblrgxrhoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhdmp4ZGxrdmpwYmxyZ3hyaG9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NjAwMjQsImV4cCI6MjA2MTEzNjAyNH0.f3Kxyd17OwGXytWNVDTtK-LsNf41700hBCwk_RVhQFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);